### PR TITLE
Fixed #15800 - Dropdown | onBlur event is emitted when the user clicks…

### LINKED ISSUE #15800: Dropdown: onBlur event is emitted when the user clicks the dropdown arrow
### Describe the bug

When the user clicks the expand arrow in a focused dropdown, the blur event is emitted.

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/hhqsns?file=src%2Fapp%2Fdropdown-basic-demo.html

### Angular version

17.1.2

### PrimeNG version

17.18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Set a dropdown to autofocus
2. Add an onBlur event emitter
3. While the dropdown is focused, click on the dropdown arrow

### Expected behavior

The blur event should be emitted only when the user clicks outside the dropdown element. The dropdown arrow is part of the dropdown.

### PR DESCRIPTION
**Pull request by leonidasdel**
Fixes [#15800](https://github.com/primefaces/primeng/issues/15800)

### CODE REVIEW

File: src/app/components/dropdown/dropdown.ts [hunk 1]
```diff
@@ -191,7 +191,7 @@ export class DropdownItem {
                 </span>
             </ng-container>
 
-            <div class="p-dropdown-trigger" role="button" aria-label="dropdown trigger" aria-haspopup="listbox" [attr.aria-expanded]="overlayVisible ?? false" [attr.data-pc-section]="'trigger'">
+            <div class="p-dropdown-trigger" role="button" aria-label="dropdown trigger" (mousedown)="$event.preventDefault()" aria-haspopup="listbox" [attr.aria-expanded]="overlayVisible ?? false" [attr.data-pc-section]="'trigger'">
```
Comment (cetincakiroglu) [inline src/app/components/dropdown/dropdown.ts:194]: Instead of adding inline code, could you please add a new method onMouseDown and cancel the event inside.

`(mousedown)="onMouseDown($event)"`

**Review by cetincakiroglu — CHANGES_REQUESTED** [review]
I'll merge this PR after the changes.

File: src/app/components/dropdown/dropdown.ts (hunk 1 above)
Comment (leonidasdel) [reply src/app/components/dropdown/dropdown.ts]: done, let me know if it needs anything else
