### PR TITLE
fixes 15058 - keyboard navigation for tieredmenu with hidden elements

### LINKED ISSUE #15058: TieredMenu: Keyboard navigation does not skip non-visible menu items
### Describe the bug

When I use keyboard navigation in the TieredMenu component (arrow keys up/down), the items with `visible: false` are not skipped, resulting in non-visible active elements when they are selected.

### Environment

NG17, latest primeng

### Reproducer

https://stackblitz.com/edit/de3knh?file=src%2Fapp%2Fdemo%2Ftiered-menu-basic-demo.ts

### Angular version

17.2.2

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to stackblitz example
2. highlight the preview
3. hit tab to enable keyboard navigation
4. hit arrow down two times and see focus disappear (that's the non visible element)

### Expected behavior

non-visible elements are skipped in keyboard navigation

### PR DESCRIPTION
**Pull request by Nas3nmann**
Fixes #15058

### CODE REVIEW

File: src/app/components/tieredmenu/tieredmenu.ts [hunk 1]
```diff
@@ -288,7 +288,11 @@ export class TieredMenuSub {
     }
 
     getAriaPosInset(index: number) {
-        return index - this.items.slice(0, index).filter((processedItem) => this.isItemVisible(processedItem) && this.getItemProp(processedItem, 'separator')).length + 1;
+        return index - this.items.slice(0, index).filter((processedItem) => {
+            let isItemVisible = this.isItemVisible(processedItem);
```
Comment (SoyDiego) [inline src/app/components/tieredmenu/tieredmenu.ts:292]: Use `const` instead of `let` because you are not reassigning the variables

**Comment by cetincakiroglu** [comment]
Hi @Nas3nmann 

Thanks a lot for the effort and support!
