### PR TITLE
fix: fixed #18040 - cascadeselect: clicking a few times causes the co…

### LINKED ISSUE #18040: CascadeSelect: clicking a few times causes the component to freeze

### PR DESCRIPTION
**Pull request by mehmetcetin01140**
fixes #18040

### CODE REVIEW

File: packages/primeng/src/overlay/overlay.ts [hunk 1]
```diff
@@ -494,21 +494,25 @@ export class Overlay extends BaseComponent implements AfterContentInit, OnDestro
 
         switch (event.toState) {
             case 'visible':
-                this.show(container, true);
+                if (this.visible) {
+                    this.show(container, true);
+                }
                 this.bindListeners();
```
Comment (rosenthalj) [inline packages/primeng/src/overlay/overlay.ts:500]: should this.bindListeners be inside your newly added  "if block"?
