### PR TITLE
Fix Issue with frozen columns #12408

### LINKED ISSUE #15303: Component: Table #15302
### Describe the bug

https://user-images.githubusercontent.com/11733376/208727545-67866f60-7db8-4256-ae2b-43a0a178753d.mov

### Environment

Frozen Columns

### Reproducer

https://stackblitz.com/edit/qnmajp?file=package.json

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. Freeze columns to the right
2. Have at least 10 rows of data
3. See the "stairs" of columns that should be freezed

### Expected behavior

All columns should be freezed as per attribute and directive assignment.

### PR DESCRIPTION
**Pull request by Lolibai**
### Defect Fixes
Fixes #15303 

### Video with the actual issue attached

https://user-images.githubusercontent.com/11733376/208727545-67866f60-7db8-4256-ae2b-43a0a178753d.mov

### Environment

Frozen Columns

### Reproducer

Lolibai

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

Chrome 123.0.6312.123

### Steps to reproduce the behavior

1. Freeze columns to the right
2. Have at least 10 rows of data
3. See the "stairs" of columns that should be freezed

https://user-images.githubusercontent.com/11733376/208727545-67866f60-7db8-4256-ae2b-43a0a178753d.mov

### Expected behavior

All columns should be freezed as per attribute and directive assignment.

### Stackblitz

[Reproduction](https://stackblitz.com/edit/qnmajp?file=package.json)

### CODE REVIEW

**Comment by Lolibai** [comment]
Hello Prime team, 
If there is any chance to investigate the issue with frozen columns - please do. 
It is already 17th version and my team is still forking and fixing this issue - custom.
Lets elaborate on this

File: src/app/components/table/table.ts [hunk 1]
```diff
@@ -3305,11 +3305,22 @@ export class FrozenColumn implements AfterViewInit {
...
+                this.recalculateColumns();
             }, 1000);
         });
     }
 
+    @HostListener('window:resize', ['$event'])
+    recalculateColumns() {
+        const siblings = DomHandler.siblings(this.el.nativeElement);
+        const index = DomHandler.index(this.el.nativeElement);
+        const time = (siblings.length - index + 1) * 50;
```
Comment (cetincakiroglu) [inline src/app/components/table/table.ts:3317]: Why multiply by 50?

Comment (bartlomiej-dobosz) [inline src/app/components/table/table.ts:3317]: This line only work for alignFrozen='right'. And this created new issue #15852.

Comment (Lolibai) [reply src/app/components/table/table.ts:3317]: Bare minimum, I assume
