### PR TITLE
Fix Button Component: Loading and iconPosition

### LINKED ISSUE #13195: pButton: When changing the loading property of the pButton the spinner is not shown
### Describe the bug

When changing the loading state of the pButton the spinner is not shown. 

The initial loading state of the button is set to false and after changing the the state to true only an empty space is shown. The expected behavior is that the icon changes to a spinner.

This feature did work before the upgrade to PrimeNG 16. 

### Environment

I've setup a minimal stackblitz demo with Angular 16 and PrimeNG 16.

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-zhumr3?file=src%2Fmain.ts

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Firefox 114, Chrome 114

### Steps to reproduce the behavior

1. Click the "Click to change loading state" button
2. The spinner should be shown in the first button

### Expected behavior

When changing the loading property from false to true a spinner should be shown inside the button.

### LINKED ISSUE #13250: Button: custom loading icon is not displayed
### Describe the bug

Custom loading icon is not displayed. from doc sample:

image

also, the loading icon space break when the `iconPos` set to right.

image

### Environment

windows

### Reproducer

_No response_

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### LINKED ISSUE #13345: Button: Loading icon not showing when used by pButton directive
### Describe the bug

The [loading] input doesn't show the indicator when the pButton directive is used. It's working with <p-button> component.
Attached a stackblitz link, the right button is working, the left doesn't.

### Environment

macos, chrome

### Reproducer

https://stackblitz.com/edit/gyambj?file=src%2Fapp%2Fdemo%2Fbutton-loading-demo.ts

### Angular version

^16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by SoyDiego**
Fix #13250
Fix #13345
Fix #13195 

All the details are in the screenshot gif. 
I'm not sure if it's the best solution, but it works. 
It was a little bit tricky to find a solution because when it was solved in `<p-button>,` it was broken in `<button pButton>` and vice versa.

## CURRENTLY
buttons problem 2

## SOLUTION
buttons working

### CODE REVIEW

File: src/app/components/button/button.ts [hunk 1]
```diff
@@ -214,7 +214,9 @@ export class ButtonDirective implements AfterViewInit, OnDestroy {
     }
 
     getIconClass() {
-        return this.loading ? 'p-button-loading-icon ' + (this.loadingIcon ? this.loadingIcon : 'p-icon') : this._icon;
+        return this.loading
+            ? 'p-button-loading-icon ' + (this.loadingIcon ? 'pi-spin ' + this.loadingIcon : 'pi pi-spin pi-spinner')
```
Comment (GiacomoDM) [inline src/app/components/button/button.ts:218]: it might be too much to add pi-spin to the custom loading icon. 
one might have it's own spinning logic on the outside

File: src/app/components/button/button.ts [hunk 2]
```diff
@@ -238,13 +240,14 @@ export class ButtonDirective implements AfterViewInit, OnDestroy {
             (click)="onClick.emit($event)"
             (focus)="onFocus.emit($event)"
             (blur)="onBlur.emit($event)"
+            [ngStyle]="isIconPosRight ? { display: 'flex', flexDirection: 'row-reverse' } : null"
```
Comment (GiacomoDM) [inline src/app/components/button/button.ts:243]: instead of `isIconPosRight ` and all it's logic, it might be enough to put: 
```
p-button[iconPos='right'] spinnericon {
    order: 1;
}
```
in the button css

File: src/app/components/button/button.ts (hunk 1 above)
Comment (SoyDiego) [reply src/app/components/button/button.ts:218]: mmm I don't understand your point. How it's the way that you say?

Thanks for the review!

File: src/app/components/button/button.ts (hunk 2 above)
Comment (SoyDiego) [reply src/app/components/button/button.ts:243]: > instead of `isIconPosRight ` and all it's logic, it might be enough to put:
> 
> ```
> p-button[iconPos='right'] spinnericon {
>     order: 1;
> }
> ```
> 
> in the button css

If I do that, I must edit the primeng-sass-theme project because is who generate all the styles and create another PR for that

File: src/app/components/button/button.ts (hunk 1 above)
Comment (GiacomoDM) [reply src/app/components/button/button.ts:218]: You added the class 'pi-spin' to the loadingIcon (`this.loadingIcon ? 'pi-spin ' + this.loadingIcon`), but this add the default spinning to the custom icons. 
This might not be wanted, as one might have a different spinning login for it's own custom icon, an might not want the default one from the default primeng spinner. It should be the user that passes 'pi-spin ' with the rest of the string in the loadingIcon input.

File: src/app/components/button/button.ts (hunk 2 above)
Comment (GiacomoDM) [reply src/app/components/button/button.ts:243]: You are correct. 
I guess it should be up to the Prime team to decide if this should be resolved at theme level via css only or at component level here.

File: src/app/components/button/button.ts (hunk 1 above)
Comment (SoyDiego) [reply src/app/components/button/button.ts:218]: Thanks again @GiacomoDM, so you recommend remove pi-spin and leave the user write when he choose the icon?
Maybe @cetincakiroglu can orient us how to proceed in your both comments.

File: src/app/components/button/button.ts (hunk 2 above)
Comment (SoyDiego) [reply src/app/components/button/button.ts:243]: > You are correct. I guess it should be up to the Prime team to decide if this should be resolved at theme level via css only or at component level here.

Yes, maybe is a good idea. I will mention one mod to ask how to proceed :)

**Comment by tomaszatenviseio** [comment]
Will it solve this issue:
 - p-button with only label, no icon
 - custom loading icon (loadingIcon)
 - loading set to true
 => then no loading icon is displayed as the component is applying p-button-loading-label-only class (which is not true, as there is loading icon set)

Something like this:
`
<p-button
      label="Yes"
      [loading]="true"
      loadingIcon="fa-solid fa-circle-notch fa-spin"
    ></p-button>
`

**Comment by SoyDiego** [comment]
> * ding icon (loadingIcon)

thanks, this PR is open to receive your codes too. If you have a better solution, share it here.
@cetincakiroglu has a lot of work but he puts this in status `Pending Review`. And also as @GiacomoDM said in comments before maybe this component is good idea PrimeNG Teams solve it because maybe they have another idea better. My solution works, but maybe is not the best.

File: src/app/components/button/button.ts (hunk 2 above)
Comment (cetincakiroglu) [reply src/app/components/button/button.ts:243]: Hi, 

It's okay to make that by CSS

Comment (SoyDiego) [reply src/app/components/button/button.ts]: Changed! :)

**Comment by Christop406** [comment]
I'm still seeing this as an issue on v16, has this fix been released yet?

**Comment by SoyDiego** [comment]
> I'm still seeing this as an issue on v16.1.0, has this fix been released yet?

Not yet, will be in the next release. But it's fixed @Christop406
