### PR TITLE
Fixed #14783 two validations simultaneously on fileupload (File limit and max file size)

### LINKED ISSUE #14783: Chips and Timeline: Typo error 'seperator' instead 'separator'
### Describe the bug

Typo error 'seperator' instead 'separator'

image

### Environment

-

### Reproducer

-

### Angular version

Last version

### PrimeNG version

Last version

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Browser(s)

_No response_

### Steps to reproduce the behavior

https://primeng.org/chips

### Expected behavior

Typo error 'seperator' instead 'separator'

### PR DESCRIPTION
**Pull request by burhanrepos**
fixed [#14783](https://github.com/primefaces/primeng/issues/14789)

Describe the bug(issue)
In FileUpload control,

Two validations does not work simultaneously.
Tried validations as maxFileSize="1000" and fileLimit="2"
After selecting files, nothing is displayed on the control

Solution:
The issue was caused by not adding a file whose size exceeds maxFileSize when no files are in the main files array due to a filesize check. Consequently, the fileLimit check failed. Now, this code checks both maxFileSize and fileLimit.

### CODE REVIEW

File: src/app/components/fileupload/fileupload.ts [hunk 1]
```diff
@@ -557,11 +557,10 @@ export class FileUpload implements AfterViewInit, AfterContentInit, OnInit, OnDe
...
         this.onSelect.emit({ originalEvent: event, files: files, currentFiles: this.files });
 
-        if (this.fileLimit) {
-            this.checkFileLimit();
-        }
+         // this will check the fileLimit with the uploaded files
+        this.checkFileLimit(files);
 
-        if (this.hasFiles() && this.auto && (!(this.mode === 'advanced') || !this.isFileLimitExceeded())) {
+        if (this.hasFiles() && this.auto && !(this.mode === 'advanced') && !this.isFileLimitExceeded()) {
```
Comment (neverlose-lv) [inline src/app/components/fileupload/fileupload.ts:563]: This brokes the [auto]="true" functionality for 'advanced' mode (the default one). So by default [auto]="true" will not work. Fix required.
