### PR TITLE
fix unit test

### LINKED ISSUE #15564: Listbox unit test fix
### Describe the bug

In this [Discussion](https://github.com/orgs/primefaces/discussions/1812) . I will also look into some broken tests and where needed extend test coverage.

This issue is not a bug ticket, but simply an issue for the PR to reference.

### Environment

windows

### Reproducer

_No response_

### Angular version

17.3.6

### PrimeNG version

17.16.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v21.7.3

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by dobanisola-scottlogic**
Fixes #15564

### CODE REVIEW

File: src/app/components/inputmask/inputmask.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export const INPUTMASK_VALUE_ACCESSOR: any = {
             (keydown)="onInputKeydown($event)"
             (keypress)="onKeyPress($event)"
             pAutoFocus
-            [variant]="variant"
+            [attr.variant]="variant"
```
Comment (cetincakiroglu) [inline src/app/components/inputmask/inputmask.ts:97]: variant is an input property of pInputText, I've accidentally accepted like that. Could you please add [variant] again?

Comment (dobanisola-scottlogic) [reply src/app/components/inputmask/inputmask.ts:97]: Sure
