### PR TITLE
Toolbar: Accept documented template names #13814

### LINKED ISSUE #13814: Toolbar: Inconsistent naming and wrong documentation
### Describe the bug

There is generally an inconsistency regarding the naming of the templates (left vs. start, right vs. end). Additionally the documentation doesn't reflect the implementation of the Toolbar.

The documentation states:
> Toolbar provides start, center and end templates to place content at these sections.

The Toolbar component instead expects the component names `left`, `center` and `right`.

### Environment

-

### Reproducer

https://stackblitz.com/edit/4ijavk?file=src%2Fapp%2Fdemo%2Ftoolbar-basic-demo.html

### Angular version

16.2.0

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by anlampe**
Fixes #13814 

There is generally an inconsistency regarding the naming of the templates (left vs. start, right vs. end). Additionally the documentation doesn't reflect the implementation of the Toolbar, means it only accepts right and left as template names.

### Fix
The Toolbar now **additionally** accepts the template names `start` and `end`.

### CODE REVIEW

File: src/app/showcase/pages/toolbar/toolbardemo.ts [hunk 1]
```diff
@@ -19,6 +20,11 @@ export class ToolbarDemo {
             label: 'Basic',
             component: BasicDoc
         },
+        {
+            id: 'template',
+            label: 'Template',
```
Comment (SoyDiego) [inline src/app/showcase/pages/toolbar/toolbardemo.ts:25]: Maybe you can add a description for template section like the others sections.

image

Comment (anlampe) [reply src/app/showcase/pages/toolbar/toolbardemo.ts:25]: I have added a description, I hope it is ok now. Thanks for reviewing!

**Review by cetincakiroglu — APPROVED** [review]
