### PR TITLE
#15260: Messages component uses `closable` and `id` from `Message`

### LINKED ISSUE #15260: Component: Messages
### Describe the bug

Messages added to the Message Service do not use the `closable` property defined in the message object. They only use the `closable` property applied to the `<p-messages>` element.

This means that if you are adding multiple messages via the Message Service, you cannot have some be `closable` and some not.

### Environment

All environments

### Reproducer

https://stackblitz.com/run?file=src%2Fapp%2Fdemo%2Fmessages-service-demo.ts

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Add multiple messages to the message service
2. On the HTML `<p-messages` element **do not** set a value for `closable` (default is `true`)
3. On one message set `closable: true`
4. On another message set `closable: false`
5. Both messages will be closable (default behavior)

### Expected behavior

Message 1 should be closable 
Message 2 should not be closable

### PR DESCRIPTION
**Pull request by jacver**
### Defect Fixes
#15260

`<p-messages>` element does not use `msg.closable` in the `*ngIf`. This means that when adding multiple messages to the service, you cannot have some closable and others not closable.

This PR adds the logic and updates the documentation to fix this and allow the ID attribute to be set from the `Message` object.

### CODE REVIEW

File: src/app/components/messages/messages.ts [hunk 1]
```diff
@@ -58,9 +58,9 @@ import { Subscription, timer } from 'rxjs';
                         </ng-container>
                         <ng-template #escapeOut>
                             <span *ngIf="msg.summary" class="p-message-summary" [attr.data-pc-section]="'summary'">{{ msg.summary }}</span>
-                            <span *ngIf="msg.detail" class="p-message-detail" [attr.data-pc-section]="'detail'">{{ msg.detail }}</span>
+                            <span *ngIf="msg.detail" class="p-message-detail" [attr.data-pc-section]="'detail'">{{ msg.detail }} test</span>
```
Comment (rosenthalj) [inline src/app/components/messages/messages.ts:61]: remove:   **` test`**

File: src/app/components/messages/messages.ts [hunk 2]
```diff
@@ -58,9 +58,9 @@ import { Subscription, timer } from 'rxjs';
...
                         </ng-template>
-                        <button class="p-message-close p-link" (click)="removeMessage(i)" *ngIf="closable" type="button" pRipple [attr.aria-label]="closeAriaLabel" [attr.data-pc-section]="'closebutton'">
+                        <button class="p-message-close p-link" (click)="removeMessage(i)" *ngIf="msg.closable || (closable && msg.closable)" type="button" pRipple [attr.aria-label]="closeAriaLabel" [attr.data-pc-section]="'closebutton'">
```
Comment (rosenthalj) [inline src/app/components/messages/messages.ts:63]: replace:
`*ngIf="msg.closable || (closable && msg.closable)"`
with
`*ngIf="closable && (msg.closable ?? true)"`

File: src/app/showcase/doc/messages/servicedoc.ts [hunk 3]
```diff
@@ -32,8 +32,8 @@ export class ServiceDoc {
 
     addMultiple() {
         this.messageService.addAll([
-            { severity: 'success', summary: 'Service Message', detail: 'Via MessageService' },
-            { severity: 'info', summary: 'Info Message', detail: 'Via MessageService' }
+            { severity: 'success', summary: 'Service Message', detail: 'Via MessageService', closable: true },
```
Comment (rosenthalj) [inline src/app/showcase/doc/messages/servicedoc.ts:35]: remove this change.  No need to explicitly set closable

File: src/app/showcase/doc/messages/servicedoc.ts [hunk 4]
```diff
@@ -32,8 +32,8 @@ export class ServiceDoc {
...
+            { severity: 'info', summary: 'Info Message', detail: 'Via MessageService', closable: false }
```
Comment (rosenthalj) [inline src/app/showcase/doc/messages/servicedoc.ts:36]: remove this change.  No need to explicitly set closable

File: src/app/showcase/doc/messages/servicedoc.ts [hunk 5]
```diff
@@ -75,8 +75,8 @@ export class MessagesServiceDemo {
 
     addMultiple() {
         this.messageService.addAll([
-            {severity:'success', summary:'Service Message', detail:'Via MessageService'},
-            {severity:'info', summary:'Info Message', detail:'Via MessageService'}
+            { severity: 'success', summary: 'Service Message', detail: 'Via MessageService', closable: true },
```
Comment (rosenthalj) [inline src/app/showcase/doc/messages/servicedoc.ts:78]: remove this change.  No need to explicitly set closable

File: src/app/showcase/doc/messages/servicedoc.ts [hunk 6]
```diff
@@ -75,8 +75,8 @@ export class MessagesServiceDemo {
...
+            { severity: 'info', summary: 'Info Message', detail: 'Via MessageService', closable: false }
```
Comment (rosenthalj) [inline src/app/showcase/doc/messages/servicedoc.ts:79]: remove this change.  No need to explicitly set closable

File: src/app/showcase/doc/messages/servicedoc.ts (hunk 5 above)
Comment (jacver) [reply src/app/showcase/doc/messages/servicedoc.ts]: Agreed, it helps for clarity in my use case, but I agree that it's probably not the most common use case. Nice catch!

File: src/app/components/messages/messages.ts [hunk 7]
```diff
@@ -42,7 +42,7 @@ import { Subscription, timer } from 'rxjs';
                     role="alert"
                     [@messageAnimation]="{ value: 'visible', params: { showTransitionParams: showTransitionOptions, hideTransitionParams: hideTransitionOptions } }"
                 >
-                    <div class="p-message-wrapper" [attr.data-pc-section]="'wrapper'">
+                    <div class="p-message-wrapper" [attr.data-pc-section]="'wrapper'" [attr.id]="msg.id || null">
```
Comment (rosenthalj) [inline src/app/components/messages/messages.ts:45]: ok, but this addressees a different issue

File: src/app/components/messages/messages.ts [hunk 8]
```diff
@@ -60,7 +60,7 @@ import { Subscription, timer } from 'rxjs';
                             <span *ngIf="msg.summary" class="p-message-summary" [attr.data-pc-section]="'summary'">{{ msg.summary }}</span>
                             <span *ngIf="msg.detail" class="p-message-detail" [attr.data-pc-section]="'detail'">{{ msg.detail }}</span>
                         </ng-template>
-                        <button class="p-message-close p-link" (click)="removeMessage(i)" *ngIf="closable" type="button" pRipple [attr.aria-label]="closeAriaLabel" [attr.data-pc-section]="'closebutton'">
+                        <button class="p-message-close p-link" (click)="removeMessage(i)" *ngIf="closable && (msg.closable ?? true)" type="button" pRipple [attr.aria-label]="closeAriaLabel" [attr.data-pc-section]="'closebutton'">
```
Comment (rosenthalj) [inline src/app/components/messages/messages.ts:63]: ok

File: src/app/showcase/doc/apidoc/index.json [hunk 9]
```diff
@@ -1313,7 +1313,7 @@
             "values": [
                 {
                     "name": "Message",
-                    "description": "Deines valid options for the message.",
+                    "description": "Defines valid options for the message.",
```
Comment (rosenthalj) [inline src/app/showcase/doc/apidoc/index.json:1316]: good

**Review by rosenthalj — APPROVED** [review]
