### PR TITLE
fix: #18062 MultiSelect is removing previously selected values if sel…

### LINKED ISSUE #18062: MultiSelect is removing previously selected values if select all is checked after search
### Describe the bug

Current behavior

Select any items from P-Multiselect.

Type for search on Search bar, it will show some results, Click on Select all.

In this case, I have previously selected two items, and now after my search result, I am selecting two more by selecting all. By doing so, it is replacing my old search values, and showing I have selected only two items.

### Pull Request Link

_No response_

### Reason for not contributing a PR

- [x] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Other Reason

_No response_

### Reproducer

https://stackblitz.com/edit/github-eavce3k6?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Environment

Window

### Angular version

^17.X.X

### PrimeNG version

v19

### Node version

19

### Browser(s)

Chrome

### Steps to reproduce the behavior

Select any items from P-Multiselect. --> Type for search on Search bar, it will show some results, --> Click on Select all. --> after select all it removed the previous selection and keep the new ones.

### Expected behavior

In this case, I have previously selected two items, and now after my search result, I am selecting two more by selecting all. By doing so, it is replacing my old search values, and showing I have selected only two items

### PR DESCRIPTION
**Pull request by mehmetcetin01140**
fixes #18062

### CODE REVIEW

File: packages/primeng/src/multiselect/multiselect.ts [hunk 1]
```diff
@@ -2000,7 +2000,9 @@ export class MultiSelect extends BaseComponent implements OnInit, AfterViewInit,
                 ? this.visibleOptions().filter((option) => !this.isValidOption(option) && this.isSelected(option))
                 : this.visibleOptions().filter((option) => this.isSelected(option) || this.isValidOption(option));
 
-            const optionValues = [...selectedDisabledOptions, ...visibleOptions].map((option) => this.getOptionValue(option));
+            const selectedOptionsBeforeSearch = this.filter ? this.getAllVisibleAndNonVisibleOptions().filter((option) => this.isSelected(option) && this.isValidOption(option)) : [];
+
+            const optionValues = [...(!this.allSelected() ? selectedOptionsBeforeSearch : []), ...selectedDisabledOptions, ...visibleOptions].map((option) => this.getOptionValue(option));
             const value = [...new Set(optionValues)];
```
Comment (rosenthalj) [inline packages/primeng/src/multiselect/multiselect.ts:2006]: For efficiency why not remove the conditional **!this.allSelected()** from  **const optionValues** and update the conditional in **const selectedOptionsBeforeSearch** to **(this.filter && !this.allSelected())**

Comment (mehmetcetin01140) [reply packages/primeng/src/multiselect/multiselect.ts:2006]: I already refactored the code right after committing it. Thanks a lot for the review.
