### PR TITLE
fixed #17193: fixed rendering of dynamic dialog content

### LINKED ISSUE #17193: v19 DynamicDialog:  Rendering problem when displaying Dynamic Dialog content without fix
### Describe the bug

PrimeNG's Dynamic Dialog fails to display content that doesn't have a fixed height.

The first video shows how the Dynamic Dialog fails to display a simple div (100% height and 100% width and red background)

https://github.com/user-attachments/assets/689ae37f-248c-4812-9d0a-f3bbd93af4ae

The second video shows v17 PrimeNG  using the exact same program and the Dynamic Dialog working correctly

https://github.com/user-attachments/assets/1b84b241-04c6-4fea-965d-5f8a1ffd0ca3

### Pull Request Link

_No response_

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [X] Other

### Other Reason

tbd - but this is a valid issue

### Reproducer

https://stackblitz.com/edit/vyyhpncb?file=src%2Fapp%2Fdemo%2Fproductlistdemo.ts,src%2Fapp%2Fimports.ts,src%2Fapp%2Fdynamic-dialog-example-demo.ts,src%2Fapp%2Fdemo%2Ffooter.ts,src%2Fapp%2Fdynamic-dialog-example-demo.html

### Environment

n/a

### Angular version

19

### PrimeNG version

v19

### Node version

n/a

### Browser(s)

All

### Steps to reproduce the behavior

1. Run the reproducer: https://stackblitz.com/edit/vyyhpncb?file=src%2Fapp%2Fdemo%2Fproductlistdemo.ts,src%2Fapp%2Fimports.ts,src%2Fapp%2Fdynamic-dialog-example-demo.ts,src%2Fapp%2Fdemo%2Ffooter.ts,src%2Fapp%2Fdynamic-dialog-example-demo.html
2. Click on the "Launch" button
3. A Dynamic Dialog will be displayed
-- Dialog will be the correct height and width
-- Red div in the center of the dialog will be missing

### Expected behavior

Run the same program with this v17 reproducer: https://stackblitz.com/edit/a9zz8skp?file=src%2Fapp%2Fdynamic-dialog-example-demo.ts,src%2Fapp%2Fdemo%2Fproductlistdemo.ts,src%2Fapp%2Fdynamic-dialog-example-demo.html,src%2Fapp%2Fimports.ts

After pressing the "Launch" button the Dynamic Dialog will be displayed
-- Dialog will be the correct height and width
-- A Red div in the center of the dialog will be displayed

### PR DESCRIPTION
**Pull request by rosenthalj**
This pull request fixes issue #17193

The video shows the pull request fixes the reproducer that demonstrated the bug.

https://github.com/user-attachments/assets/5b9d0aab-c4df-49e1-8605-5d83e7da881c

Note:  I manually verified that this pull request doesn't break  PrimeNG's dialog and dynamic dialog demos

### CODE REVIEW

**Comment by rosenthalj** [comment]
I believe this  pull request will also fix a similar issue with PrimeNG Dialog

File: packages/primeng/src/dialog/style/dialogstyle.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ const theme = ({ dt }) => `
 .p-dialog-content {
     overflow-y: auto;
     padding: ${dt('dialog.content.padding')};
+    flex: 1 1 auto
```
Comment (imaksp) [inline packages/primeng/src/dialog/style/dialogstyle.ts:21]: Hi, have you tried with   `flex-grow: 1;` instead of this, it is present in v17 but missing in this. also semicolon is missing.

Comment (rosenthalj) [reply packages/primeng/src/dialog/style/dialogstyle.ts]: I have  implemented the changes you suggested to be consistent with previous versions of PrimeNG.  I have confirmed the change with the original reproducer I provided in the  issue.

Note:  both **flex: 1 1 auto** and **flex-grow: 1**  and (I also tested **flex: auto**) all produced the same  positive results

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!
