### PR TITLE
fix(Column-Filter): #13596 Auto close on Click Outside does not work

### LINKED ISSUE #1359: ui-fluid breaks schedule buttons

### PR DESCRIPTION
**Pull request by denny99**
Fixes #1359

Notes for the other misc. Changes:

For some reason the other 3 files failed during the prettier check
image
So i just re ran the prettier command to format them.
As i reviewed those files i saw, that the document injection in the tiered menu was unused and cleaned up the code

### CODE REVIEW

**Comment by denny99** [comment]
Side Note: Some files i did not touch had a corrupted formatting and i had to re run prettier

**Review by SoyDiego — APPROVED** [review]

File: src/app/components/tieredmenu/tieredmenu.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ export class TieredMenuSub {
 
     @ViewChild('sublist', { static: true }) sublistViewChild: ElementRef;
 
-    constructor(@Inject(DOCUMENT) private document: Document, public el: ElementRef, public renderer: Renderer2, private cd: ChangeDetectorRef,@Inject(forwardRef(() => TieredMenu)) public tieredMenu: TieredMenu) {}
+    constructor(public el: ElementRef, public renderer: Renderer2, private cd: ChangeDetectorRef, @Inject(forwardRef(() => TieredMenu)) public tieredMenu: TieredMenu) {}
```
Comment (ashikjs) [inline src/app/components/tieredmenu/tieredmenu.ts:225]: @denny99 why we need to  remove `@Inject(DOCUMENT) private document: Document` this line

**Review by ashikjs — APPROVED** [review]

File: src/app/components/fileupload/fileupload.ts [hunk 2]
```diff
@@ -901,4 +901,4 @@ export class FileUpload implements AfterViewInit, AfterContentInit, OnInit, OnDe
     exports: [FileUpload, SharedModule, ButtonModule, ProgressBarModule, MessagesModule],
     declarations: [FileUpload]
 })
-export class FileUploadModule { }
+export class FileUploadModule {}
```
Comment (ashikjs) [inline src/app/components/fileupload/fileupload.ts:904]: @denny99  if you didn't work this file then is it need to change or remove this file any line ?

**Review by ashikjs — CHANGES_REQUESTED** [review]

File: src/app/components/tieredmenu/tieredmenu.ts (hunk 1 above)
Comment (denny99) [reply src/app/components/tieredmenu/tieredmenu.ts:225]: It was just unused, so i cleaned up the code

Comment (ashikjs) [reply src/app/components/tieredmenu/tieredmenu.ts:225]: @denny99  ok

File: src/app/components/fileupload/fileupload.ts (hunk 2 above)
Comment (denny99) [reply src/app/components/fileupload/fileupload.ts:904]: Otherwise the Pull Request Prettier Stage fails, so i just ran the prettier command to auto format the file

Comment (ashikjs) [reply src/app/components/fileupload/fileupload.ts:904]: @denny99  Good point can you mention it your PR description so PR reviewer can understand the purpose of those extra changes.

**Review by ashikjs — APPROVED** [review]

File: src/app/components/fileupload/fileupload.ts (hunk 2 above)
Comment (denny99) [reply src/app/components/fileupload/fileupload.ts:904]: Like in my very first comment above :D 
Yeah sure i can copy paste that into the description

Comment (denny99) [reply src/app/components/fileupload/fileupload.ts:904]: done

**Review by cetincakiroglu — APPROVED** [review]
