### PR TITLE
Bug #15342 - Split Button: Aria Label not correctly working

### LINKED ISSUE #15342: Split Button: Aria Label not correctly working
### Describe the bug

The ButtonProps and MenuButtonProps are not correctly defined and cannot be used currently. 

They define a property 'ariaLabel', but in the code in is accessed as 'aria-label'. 
The same problem exists for the other properties of MenuButtonProps. 

For reference see: 
- https://github.com/primefaces/primeng/blob/17.14.1/src/app/components/splitbutton/splitbutton.ts#L74
- https://github.com/primefaces/primeng/blob/17.14.1/src/app/components/splitbutton/splitbutton.interface.ts

I tested it in v17.13, but as you see in the links above, it should still exist in 17.14.1.

 

### Environment

I am using angular 17

### Reproducer

_No response_

### Angular version

17

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by maruthumj**
fixes #15342

### CODE REVIEW

File: src/app/components/splitbutton/splitbutton.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ type SplitButtonIconPosition = 'left' | 'right';
                     (click)="onDefaultButtonClick($event)"
                     [disabled]="disabled"
                     [attr.tabindex]="tabindex"
-                    [attr.aria-label]="buttonProps?.['aria-label'] || label"
+                    [ariaLabel]="buttonProps?.['ariaLabel'] || label"
```
Comment (SoyDiego) [inline src/app/components/splitbutton/splitbutton.ts:35]: I think the correct way is `attr.aria-label` in Angular. Are you sure about this change?
Maybe @cetincakiroglu can confirm it

Comment (maruthumj) [reply src/app/components/splitbutton/splitbutton.ts:35]: @SoyDiego Since we are using pbutton as a directive and pbutton has the property named "ariaLabel", we can pass the property name as "ariaLabel".

Comment (SoyDiego) [reply src/app/components/splitbutton/splitbutton.ts:35]: Thanks for clarify 😊

**Review by SoyDiego — APPROVED** [review]

File: src/app/components/splitbutton/splitbutton.ts (hunk 1 above)
Comment (maruthumj) [reply src/app/components/splitbutton/splitbutton.ts:35]: > Thanks for clarify 😊

No problem 🙂
