### PR TITLE
Fixed #14368 - Accordian : TextArea shortcuts are not working when us…

### LINKED ISSUE #14368: Accordian : TextArea shortcuts are not working when used in Accordian Panels
### Describe the bug

When Text Area components are used in a accordion panels and focus is within the text area content, the traditional keyboard shortcuts  such for using  **Shift+Home** , **Shift+End** for highlighting the text  and Home, End to move within the text area are not working and moves to next accordion instead. 
image
When focus is within the text area, text-area shortcuts should take precedence
These shortcuts work fine when the text area is outside of accordian

### Environment

Node : 20

### Reproducer

https://stackblitz.com/edit/mwq3yh?file=src%2Fapp%2Fdemo%2Faccordion-basic-demo.html

### Angular version

17.0.0

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. Goto [demo-bug](https://stackblitz.com/edit/mwq3yh?file=src%2Fapp%2Fdemo%2Faccordion-basic-demo.html)
2. move the cursor to within anywhere inside text area
3. try shortcut such as **shift+end** to highlight text till the end of line

### Expected behavior

1. Text Area **shortcuts** should work when the cursor is inside the textarea and behave similar to the functionality of [inputtextarea-demo](https://primeng.org/inputtextarea#basic)

### PR DESCRIPTION
**Pull request by bhishman-desai**
Fixes #14368

### CODE REVIEW

File: src/app/components/utils/htmlutils.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export class HTMLUtils {
```
Comment (SoyDiego) [inline src/app/components/utils/htmlutils.ts:1]: I don't know the rest of the code but in my opinion the `utils` folder should be outside `components` folder.

Comment (bhishman-desai) [reply src/app/components/utils/htmlutils.ts:1]: I just followed the current folder structure.

Comment (cetincakiroglu) [reply src/app/components/utils/htmlutils.ts:1]: Hi,

Since there isn't much code, you can remove the HTML Utils and check the tagname inside the accordion.ts.

Comment (bhishman-desai) [reply src/app/components/utils/htmlutils.ts]: Sure. Changes are made now :)
